### ISSUE TITLE
Queue::getJobs('processed') is not working

### ISSUE THREAD

**Issue by suzol10** [jenwachter/php-redis-queue#3]
only `pending` and `processing` jobs are tracked in a list
it would be really great if the `processed` jobs could be retrieved as well to monitor (in UI for example) `failed` and `successful` jobs, which would allow the rerun of jobs too if necessary
I have tried with the JobGroups, but it's difficult if you can just work with IDs

**Comment by jenwachter** [comment]
Thanks for the feedback and I agree the CLI is definitely an area that could use improvement. Currently, the status of jobs isn't tracked in any meaningful way in the queue; the only place job status is tracked is on the jobs themselves. I rely on my logging system to track and rerun any failed jobs, but knowing which jobs succeeded and failed within each queue is something the CLI should certainly be able to do.

If it's helpful, the reason I include this from the outset is that after a job runs, the job data is set to [expire](https://redis.io/docs/latest/commands/expire/) after 24 hours for successful jobs and 7 days for failed jobs. If a list of failed/successful jobs were maintained, you would end up with a bunch of IDs that point to expired job data... though it might be possible to keep a list (of sorts) with processed job IDs and expire those IDs when their job data expires, but I would need to look into that.

This project is a bit of a back-burner one for me right now, but I'll make a note to look into this over the next few weeks.

If you're interested in pursuing a solution on your own, I'd welcome a pull request!

**Comment by zoltansuto** [comment]
hi @jenwachter , 
yes, I looked into it. I'm not asking you to track the successful and the failed jobs. I think it would be perfectly sufficient, if `processed jobs` would be a list as well - like the other 2 statuses - , instead of the number, then we could filter the successful and the failed ones from that list. Right now it's not possible to get the list of processed jobs (especially for a queue) with the existing methods (unless I missed someting). the rest then I can take care of from my app. but this is more of a core change. you could still keep the expire times for them for efficiency
what do you think @jenwachter ?

I will try to do a PR as soon as I have some time :) unfotunately I'm really busy integrating your package into my project ;-). I really like how lightweight it is compared to others

**Comment by jenwachter** [comment]
I gotchu. The goal is to have a list containing processed job IDs.

Also, thanks! That's a big reason I built my own... every other solution was complex/bloated for what I needed.

**Comment by jenwachter** [comment]
Sorry for the delay in responding to this issue. I had to hop back on this project for a bit, so it seemed like a good time to address this.

In [v1.6.0](https://github.com/jenwachter/php-redis-queue/releases/tag/v1.6.0), a list of processed jobs is now available. I also updated the CLI to reflect this change. Using the `queues:jobs` command:

* `prq queues:jobs <queuename>` returns list of pending jobs (as it did before)
* New: `prq queues:jobs <queuename> processed` returns a list of processed jobs
* New: `prq queues:jobs <queuename> processed success` returns a list of processed jobs that were successful
* New: `prq queues:jobs <queuename> processed failed` returns a list of processed jobs that failed

**Comment by jenwachter** [comment]
One last thing! Because the datatype for `processed` has changed, make sure to install [v1.6.1](https://github.com/jenwachter/php-redis-queue/releases/tag/v1.6.1). ~~you'll need to remove keys that follow this format from your redis store.~~
